export type WikiPageType = "source" | "entity" | "concept" | "question";

export const WIKI_PAGE_TYPES: readonly WikiPageType[] = [
	"source",
	"entity",
	"concept",
	"question",
];

export const WIKI_PAGE_TYPE_LABELS: Record<WikiPageType, string> = {
	source: "sources",
	entity: "entities",
	concept: "concepts",
	question: "questions",
};

export type WikiStatus =
	| "seed"
	| "developing"
	| "mature"
	| "evergreen"
	| "unknown";

export interface NodeMeta {
	path: string;
	basename: string;
	title: string;
	type: WikiPageType;
	status: WikiStatus;
	/** source_type / entity_type / complexity (subtype depending on type). Empty string if absent */
	subType: string;
	/** Stub auto-generated by lint (tags: lint-stub) */
	isLintStub: boolean;
	/** frontmatter created (YYYY-MM-DD). Empty string if absent */
	created: string;
	/** frontmatter updated (YYYY-MM-DD). Empty string if absent */
	updated: string;
	/** Distinct destination pages (unique neighbors). */
	inDeg: number;
	outDeg: number;
	/** Resolved link instances (sum of edge counts). */
	inCount: number;
	outCount: number;
	/** Number of resolved one-way references to outside the wiki (papers/ structures/ etc.) */
	outsideRefs: number;
}

export interface WikiEdge {
	src: string;
	dst: string;
	count: number;
}

export type DeadCause =
	| "file-ref"
	| "missing-at-prefix"
	| "missing-source"
	| "missing-page";

export const DEAD_CAUSE_LABELS: Record<DeadCause, string> = {
	"file-ref": "File reference",
	"missing-at-prefix": "Missing @ prefix",
	"missing-source": "Missing source (@-prefixed)",
	"missing-page": "Missing page",
};

export interface DeadTarget {
	target: string;
	cause: DeadCause;
	/** Total number of references (including duplicate references) */
	refs: number;
	/** Paths of referrer pages */
	referrers: string[];
}

/* --- Shared types for the timeline features (Growth Timeline / two-point Diff) --- */

export type TimeMode = "replay" | "diff";

/** Role classification of a node/edge on the timeline */
export type TimeClass = "hidden" | "new" | "updated" | "existing";

/**
 * Time filter context. All dates are epoch day counts (UTC, integer days).
 * replay: shows everything up to time t, highlighting appearances within the
 * last recentWindow days as "new".
 * diff: compares time a and b (a < b); classifies as "new" if born in (a, b],
 * and as "updated" if updated in (a, b].
 */
export type TimeFilterContext =
	| { mode: "replay"; t: number; recentWindow: number }
	| { mode: "diff"; a: number; b: number };

/**
 * State of the time controls (slider/tabs/presets).
 * All indices refer into the TimelineModel.days array.
 */
export interface TimeControlsState {
	mode: TimeMode;
	/** replay: current time point (index into days) */
	tIndex: number;
	/** diff: comparison start/end points (indices into days, aIndex < bIndex) */
	aIndex: number;
	bIndex: number;
	/** replay: recent highlight window (in days) */
	recentWindowDays: number;
}

/** One parsed operation entry from wiki/log.md */
export interface LogEvent {
	/** YYYY-MM-DD */
	date: string;
	/** Operation type (ingest-paper / ingest / wiki-query deep, etc.) */
	op: string;
	title: string;
	/** Resolved node paths from Pages created (wiki layer only) */
	createdPaths: string[];
	/** Resolved node paths from Pages updated (wiki layer only) */
	updatedPaths: string[];
}

export interface LogParseResult {
	/** In log.md's listed order (newest first) */
	events: LogEvent[];
	/** Number of entries whose heading was found but couldn't be interpreted and were skipped */
	failedCount: number;
}

export interface IndexStats {
	builtAt: number;
	buildMs: number;
	fileCount: number;
	edgeCount: number;
	edgeInstanceCount: number;
	deadTargetCount: number;
	deadRefCount: number;
}
